server:
  port: 9999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: test
            uri: lb://experience-service
            predicates:
              - Path=/api/v1/es/**
              - Method=



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
