server:
  port: 9999

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/security-realm
          jwk-set-uri: http://localhost:8080/realms/security-realm/protocol/openid-connect/certs
  #      client:
  #        registration:
  #          keycloak:
  #            client-id: security-client
  #            client-secret: jGd7LgsZI4ibifuyR2DFxPVyRv0vjjlZ
  #            scope: openid
  #            authorization-grant-type: password
  cloud:
    gateway:
      routes:
        - id: exs
          uri: lb://experience-service
          predicates:
            - Path=/api/v1/exs/**

        - id: ins
          uri: lb://industry-service
          predicates:
            - Path=/api/v1/ins/**

        - id: security
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**