server:
  port: 9999

spring:
  application:
    name: api-gateway
  security:
    jwt:
      secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  cloud:
    gateway:
      routes:
        - id: exs
          uri: lb://experience-service
          predicates:
            - Path=/api/v1/exs/**
          filters:
            - name: AuthenticationFilter

        - id: ins
          uri: lb://industry-service
          predicates:
            - Path=/api/v1/ins/**
          filters:
            - name: AuthenticationFilter

        - id: security
          uri: lb://security-service
          predicates:
            - Path=/api/v1/auth/**