server:
  port: 9999

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: exs
          uri: lb://experience-service
          predicates:
            - Path=/api/v1/exs/**

        - id: ins
          uri: lb://industry-service
          predicates:
            - Path=/api/v1/ins/**