server:
  port: 0

spring:
  application:
    name: industry-service
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/security-realm
          jwk-set-uri: http://localhost:8080/realms/security-realm/protocol/openid-connect/certs