server:
  port: 8081

spring:
  application:
    name: keycloak-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/security-realm
#  main:
#    web-application-type: reactive
  #  main:
#    security:
#      keycloak:
#        oauth2:
#          keyset:
#            issuer-uri: http://localhost:8080/realms/security-realm/protocol/openid-connect/certs

#  security:
#    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: security-client
#            client-secret: jGd7LgsZI4ibifuyR2DFxPVyRv0vjjlZ
#            scope: openid
#            authorization-grant-type: password
#        provider:
#          keycloak:
#            token-uri: http://localhost:8080/realms/security-realm/protocol/openid-connect/token
#            issuer-uri: http://localhost:8080/realms/security-realm/protocol/openid-connect/certs

  #    jwt:
#      secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw