server:
  port: 0

spring:
  application:
    name: security-service

  security:
    #    cors:
    #      allowedOrigins: ${CORS_ALLOWED_ORIGINS}
    #      allowedMethods: ${CORS_ALLOWED_METHODS}
    jwt:
      secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
      expired: 3600000
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:security_service