server:
  port: 0

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8081/eureka/

spring:
  application:
    name: experience_service
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
#    parameters:
#      searchPath: "experience-service/src/main/resources/db/changelog"
  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:experience_service

#logging:
#  level:
#    liquibase: DEBUG