server:
  port: 0

spring:
  application:
    name: experience_service

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:experience_service
