server:
  port: 0

spring:
  application:
    name: experience-service
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8888/realms/security-realm/protocol/openid-connect/certs

  kafka:
    producer:
      bootstrap-servers: localhost:9091
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.LongSerializer
      properties:
        enable:
          idempotence: true
        retention:
          ms: 604800000

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    show-sql: true
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl: validate
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: jdbc:h2:mem:experience_service

resilience4j:
  circuitbreaker:
    instances:
      industry-service:
        failureRateThreshold: 50
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 2
        minimumNumberOfCalls: 1
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      industry-service:
        maxAttempts: 3
        waitDuration: 3000